name: CI

on: [push, pull_request]

jobs:

  testsuite:
    name: all tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.2', '7.3', '7.4' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: PHP=${{ matrix.php }} ./Build/Scripts/runTests.sh composer install

      - name: Lint PHP
        run: PHP=${{ matrix.php }} ./Build/Scripts/runTests.sh composer ci:php:lint

      - name: PHP Coding Standards Fixer
        run: PHP=${{ matrix.php }} ./Build/Scripts/runTests.sh composer ci:php:cs

      - name: PHPStan
        run: PHP=${{ matrix.php }} ./Build/Scripts/runTests.sh composer ci:php:stan

      - name: PHP Mess Detector
        run: PHP=${{ matrix.php }} ./Build/Scripts/runTests.sh composer ci:php:md
